### ISSUE TITLE
Add bibtex files or references to them

### ISSUE THREAD

**Issue by fergunet** [JJ/modeling-volunteer-computing#1]
Files javascript.bib, ror-js.bib, and GA-general.bib are not in the repo

**Comment by JJ** [comment]
They are in geneura/papers You just have to add it to the path.

2015-02-08 18:37 GMT+01:00 Pablo García Sánchez notifications@github.com:

> Assigned #1 https://github.com/JJ/modeling-volunteer-computing/issues/1
> to @JJ https://github.com/JJ.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JJ/modeling-volunteer-computing/issues/1#event-232123165
> .

## 

JJ

**Comment by fergunet** [comment]
You are right, forgot to export the BIBINPUTS environment variable.
