### ISSUE TITLE
Evosoft: Add ACM Classification Keywords

### ISSUE THREAD

**Issue by unintendedbear** [JJ/modeling-volunteer-computing#122]
Reviewer 2 says they are missing.

**Comment by mariosky** [comment]
How about? 

CCS →  Human-centered computing →  Collaborative and social computing →  Collaborative and social computing systems and tools →  Open source software 

http://dl.acm.org/ccs/ccs.cfm

**Comment by mariosky** [comment]
CCS →  Computing methodologies →  Artificial intelligence →  Distributed artificial intelligence →  Multi-agent systems

**Comment by JJ** [comment]
OK

2016-05-03 16:34 GMT+02:00 Mario Garcia Valdez notifications@github.com:

> CCS → Computing methodologies → Artificial intelligence → Distributed
> artificial intelligence → Multi-agent systems
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/JJ/modeling-volunteer-computing/issues/122#issuecomment-216548346

## 

JJ

**Comment by mariosky** [comment]
Classification added, please compile and check I don´t have Latex right now. @JJ @unintendedbear

**Comment by JJ** [comment]
I don't think that's needed on the paper, just on the website... I have
added what you have said.

2016-05-03 18:38 GMT+02:00 Mario Garcia Valdez notifications@github.com:

> Classification added, please compile and check I don´t have Latex right
> now. @JJ https://github.com/JJ @unintendedbear
> https://github.com/unintendedbear
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/JJ/modeling-volunteer-computing/issues/122#issuecomment-216588092

## 

JJ

**Comment by mariosky** [comment]
Ok,  but on the Gecco 2016 site: 

The ACM Classification section and Author Keywords are mandatory to be included on the first page of your submission.

http://gecco-2016.sigevo.org/index.html/Papers+submission+instruction

Maybe the reviewer was to referring to that

**Comment by JJ** [comment]
Apparently, that was a mistake
http://www.sheridanprinting.com/typedept/gecco3.htm

**Comment by mariosky** [comment]
Ok I will remove the section from the paper,
