### ISSUE TITLE
Evosoft: Check figures 3 and 4

### ISSUE THREAD

**Issue by unintendedbear** [JJ/modeling-volunteer-computing#123]
So that we address these comments form reviewer 2:
- Figure 3 could be resized to fit into a single column
- Figure 4 shows "Time in seconds" -> should be "Time in milliseconds"; also, the range on the y-axis could be decreased to [600, 1600]
- Both Figure 3 and 4 show boxplots in different styles; consistent plotting (preferrably in the style of Figure 4) would be better

**Comment by fergunet** [comment]
I've changed the python script to generate again Figure 4, but I do not know who created figure 3. @mariosky @JJ ? (however, I think we can leave as it is, it's more an aesthetic issue...), so, close this issue if you want.

**Comment by JJ** [comment]
OK, I'll check and close. Where's the Python script?
