### ISSUE TITLE
Create a system diagram

### ISSUE THREAD

**Issue by fergunet** [JJ/modeling-volunteer-computing#13]
I can do it with a fancy graphic editor, but I would like a brief description of the system

**Comment by JJ** [comment]
Please do it.

**Comment by JJ** [comment]
Pablo ¿vas a hacer esto? Me gustaría enviarlo ya.

**Comment by fergunet** [comment]
Pensaba que era para el día 6, ahora me pongo y te lo mando.

2015-07-31 18:24 GMT+02:00 Juan Julián Merelo Guervós <
notifications@github.com>:

> Pablo ¿vas a hacer esto? Me gustaría enviarlo ya.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JJ/modeling-volunteer-computing/issues/13#issuecomment-126740477
> .

## 

Dr. Pablo García Sánchez
University of Granada
http://www.ugr.es/~pablogarcia

**Comment by JJ** [comment]
Es para el quince, pero las vacaciones empiezan ya.

El 31 de julio de 2015, 18:27, Pablo García Sánchez <
notifications@github.com> escribió:

> Pensaba que era para el día 6, ahora me pongo y te lo mando.
> 
> 2015-07-31 18:24 GMT+02:00 Juan Julián Merelo Guervós <
> notifications@github.com>:
> 
> > Pablo ¿vas a hacer esto? Me gustaría enviarlo ya.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/JJ/modeling-volunteer-computing/issues/13#issuecomment-126740477
> > 
> > .
> 
> ## 
> 
> Dr. Pablo García Sánchez
> University of Granada
> http://www.ugr.es/~pablogarcia
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JJ/modeling-volunteer-computing/issues/13#issuecomment-126742890
> .

## 

JJ

**Comment by vrivas** [comment]
Pues yo estaba repasando el inglés, que necesita un buen repaso... al menos la versión a la que ayer le hice el fork.
Si lo vais a mandar ya, dudo que me dé tiempo, así que suerte con el artículo!

**Comment by JJ** [comment]
No está ni terminada la primera versión. Si quieres editar algo, adelante.
Me toca paper en vez de novela estas vacaciones.

El 1 de agosto de 2015, 14:12, Víctor Manuel Rivas Santos <
notifications@github.com> escribió:

> Pues yo estaba repasando el inglés, que necesita un buen repaso... al
> menos la versión a la que ayer le hice el fork.
> Si lo vais a mandar ya, dudo que me dé tiempo, así que suerte con el
> artículo!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JJ/modeling-volunteer-computing/issues/13#issuecomment-126908212
> .

## 

JJ
