### ISSUE TITLE
Propongo ponerme a trabajar en:

### ISSUE THREAD

**Issue by mariosky** [JJ/modeling-volunteer-computing#15]
Creo que falta esto en lo que podría ayudar, si ya está alguien trabajando en algo o creen que no es
necesario me dicen es propuesta:
1. Una descripción detallada de los servicios web del servidor. 
2. Una descripción detallada del los clientes resaltando lo nuevo de web workers.
3. Los algoritmos de los procesos más importantes.

**Comment by JJ** [comment]
El 3 de agosto de 2015, 20:00, Mario Garcia Valdez <notifications@github.com

> escribió:
> 
> Creo que falta esto en lo que podría ayudar, si ya está alguien trabajando
> en algo o creen que no es
> necesario me dicen es propuesta:
> 1. Una descripción detallada de los servicios web del servidor.
> 2. Una descripción detallada del los clientes resaltando lo nuevo de
>    web workers.
> 3. Los algoritmos de los procesos más importantes.
> 
> Hay una pequeña descripción de todo ello ya en el paper, con gráfico.
> Puedes revisarla y añadirle.Un cosa que sí haría falta es más ejecuciones
> del algoritmo "clásico". Desde esta mañana llevo solo una docena y
> necesitaría ciento y pico (aunque imposible hacer mil y pico como con
> cartones.mx). Por favor, difundidlo a ver si etre hoy y mañana tenemos la
> menos 50.

JJ

**Comment by mariosky** [comment]
Ok!

2015-08-03 11:09 GMT-07:00 Juan Julián Merelo Guervós <
notifications@github.com>:
