### ISSUE TITLE
Sobre los plots

### ISSUE THREAD

**Issue by mariosky** [JJ/modeling-volunteer-computing#16]
JJ, 
En el caso del experimento donde no sabemos los IPs, ¿estadísticamente puede 
verse a cada worker como un IP? Creo que la tendencia debería ser la misma ya que
cada IP puede tener dos workers,  además se cubre  el caso de usuarios que tengan varias
pestañas o instancias del navegador trabajando.

Sobre los plots:

Hay unos que muestran los tiempos de ejecución y otros que se enfocan en la dinámica 
de los voluntarios. Para el caso de tiempo de ejecución se podrían hacer experimentos más
controlados con números específicos de navegadores por periodo de tiempo.

Hay un plot donde se muestra el número de IPs, ¿esto se hizo por periodo de tiempo?
Por ejemplo, en determinado experimento hubo 16 IPs ¿durante todo el experimento?
Se supone que cada experimento es local al navegador, ¿entonces en determinado momento
se consideran los experimentos que se estén ejecutando al mismo tiempo?

No entiendo bien esos plots. 

Saludos

**Comment by JJ** [comment]
El 3 de agosto de 2015, 20:10, Mario Garcia Valdez <notifications@github.com

> escribió:
> 
> JJ,
> En el caso del experimento donde no sabemos los IPs, ¿estadísticamente
> puede
> verse a cada worker como un IP? Creo que la tendencia debería ser la misma
> ya que

Eso es lo que he hecho, al final. Un uuid es único, así que eso es lo que
se usa.

> Sobre los plots:
> 
> Hay unos que muestran los tiempos de ejecución y otros que se enfocan en
> la dinámica
> de los voluntarios. Para el caso de tiempo de ejecución se podrían hacer
> experimentos más
> controlados con números específicos de navegadores por periodo de tiempo.

Sería trabajo futuro. Es interesante saber el overhead sobre un cliente
node normal, pero no se trata de optimizar el tiempo ahora, sino de saber
cómo se comporta la gente.

> Hay un plot donde se muestra el número de IPs, ¿esto se hizo por periodo
> de tiempo?

No, por experimento.

> Por ejemplo, en determinado experimento hubo 16 IPs ¿durante todo el
> experimento?

Sí, es el máximo.

> Se supone que cada experimento es local al navegador, ¿entonces en
> determinado momento
> se consideran los experimentos que se estén ejecutando al mismo tiempo?

Claro. Todos intercambian información a través del servidor.

**Comment by pacastillo** [comment]
Creo que durante el curso, ya con alumnos a los que podemos pedirles su colaboración, sí podríamos hacer experimentos controlados, con N navegadores, e incluso de diferente tipo (PC, móviles, etc).

**Comment by JJ** [comment]
Como os digo, sería útil para ver el escalado, sobre todo por el servidor,
que llegará un momento que no aguante. Pero para trabajo futuro.
