### ISSUE TITLE
Falta acordar los nombres de librerías y proyectos.

### ISSUE THREAD

**Issue by mariosky** [JJ/modeling-volunteer-computing#20]
En los quen no hay uniformidad propongo:

Node.js
En el texto hay todavía NodeJS, node.js, Node.js,  según mi investigación (nodejs.org,wikipedia) es Node.js

Express 
Yo había puesto  express, lo correcto es Express 
Me falta corregir también la figura del algoritmo. Puse UIID en lugar de UUID. 
Pero ahí tengo express con minúsculas.

Chart.js
chart.js es Chart.js (Incluso así se llama la librería)

**Comment by JJ** [comment]
OK, adelante.

El 10 de agosto de 2015, 19:32, Mario Garcia Valdez <
notifications@github.com> escribió:

> En los no hay uniformidad propongo:
> 
> Node.js
> En el texto hay todavía NodeJS, node.js, Node.js, según mi investigación (
> nodejs.org,wikipedia) es Node.js
> 
> Express
> Yo había puesto express, lo correcto es Express
> Me falta corregir también la figura del algoritmo. Puse UIID en lugar de
> UUID.
> Pero ahí tengo express con minúsculas.
> 
> Chart.js
> chart.js es Chart.js (Incluso así se llama la librería)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JJ/modeling-volunteer-computing/issues/20.

## 

JJ
