### ISSUE TITLE
Final review

### ISSUE THREAD

**Issue by JJ** [JJ/modeling-volunteer-computing#22]
I'll submit it tomorrow. Please @fergunet @pacastillo @mariosky give it a final look. Mario, please register at https://easychair.org/conferences/?conf=ieeecimcisw2016 so that I can add you easily as an author.

**Comment by mariosky** [comment]
Ok, I just logged in fine.

**Comment by mariosky** [comment]
Algunos comentarios después de darle otra leída:

El párrafo que pongo a continuación creo que no aporta mucho al enfoque
del paper. Sobre todo eso de  "these issues are related to security as well as
safety," 

This kind of systems must solve a series of issues before even starting to
measure their performance; these issues are related to security as well as
safety, which introduces a {\em social} aspect to the design of a
computing system that makes it a {\em techno-social system}.
In this paper our intention is to
present the {\sf NodIO} framework and analyze it from two different
angles: the purely technical angle, including the decisions that went
into its features, and the social angle, to account on how the persons
that voluntarily choose to enter the web page that runs the system
determine its performance and how it can be modeled and, eventually,
predicted.

Hay dos párrafos seguidos donde se usa el On the other hand, no sé sea aceptable.

On the other hand, we are also interested in measuring the performance
of volunteer computing systems, an area in which there have been

On the other hand, measuring performance of the resulting metacomputer
involves understanding the dynamics of this kind of systems. Initial

Se podría agregar después dependiendo del espacio:
-Una imagen de la interfaz de usuario, sobre todo para que se den una idea.
-Detalles de las prestaciones de los servidores, no se habla de donde se ejecutó el 
segundo experimento.
-No se menciona en el SoA si hay algún trabajo previo de los Web Workers, se podría
mencionar la tesis de mi alumna que uso web workers para hacer un algoritmo EA 
con EvoSpace aunque no publicamos nada.

A mi me gusta mucho el trabajo, gracias por invitarme a participar.

**Comment by JJ** [comment]
Mejor que hagas todos los cambios en el propio paper, es más fácil así.

2015-08-12 6:56 GMT+02:00 Mario Garcia Valdez notifications@github.com:

> Algunos comentarios después de darle otra leída:
> 
> El párrafo que pongo a continuación creo que no aporta mucho al enfoque
> del paper. Sobre todo eso de "these issues are related to security as well
> as
> safety,"
> 
> This kind of systems must solve a series of issues before even starting to
> measure their performance; these issues are related to security as well as
> safety, which introduces a {\em social} aspect to the design of a
> computing system that makes it a {\em techno-social system}.
> In this paper our intention is to
> present the {\sf NodIO} framework and analyze it from two different
> angles: the purely technical angle, including the decisions that went
> into its features, and the social angle, to account on how the persons
> that voluntarily choose to enter the web page that runs the system
> determine its performance and how it can be modeled and, eventually,
> predicted.
> 
> Hay dos párrafos seguidos donde se usa el On the other hand, no sé sea
> aceptable.
> 
> On the other hand, we are also interested in measuring the performance
> of volunteer computing systems, an area in which there have been
> 
> On the other hand, measuring performance of the resulting metacomputer
> involves understanding the dynamics of this kind of systems. Initial
> 
> Se podría agregar después dependiendo del espacio:
> -Una imagen de la interfaz de usuario, sobre todo para que se den una idea.
> -Detalles de las prestaciones de los servidores, no se habla de donde se
> ejecutó el
> segundo experimento.
> -No se menciona en el SoA si hay algún trabajo previo de los Web Workers,
> se podría
> mencionar la tesis de mi alumna que uso web workers para hacer un
> algoritmo EA
> con EvoSpace aunque no publicamos nada.
> 
> A mi me gusta mucho el trabajo, gracias por invitarme a participar.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JJ/modeling-volunteer-computing/issues/22#issuecomment-130162286
> .

## 

JJ
