### ISSUE TITLE
Error trying to compile the latex files in GECCO

### ISSUE THREAD

**Issue by marco-fp** [JJ/modeling-volunteer-computing#28]
When trying to compile the latex files in GECCO dir I get the following error:

"! LaTeX Error: File `comment.sty' not found."

Using Gummi editor with: pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian) to compile.

Would be nice to have a compiled version of the papers on the directory to avoid similar errors due to incompatibilities.

**Comment by JJ** [comment]
Prueba a instalar tetex-live-extra a ver si está incluido.

**Comment by JJ** [comment]
Did you fix that? Can I close it?

**Comment by marco-fp** [comment]
Couldn't make it work, but probably was something about my machine.
