### ISSUE TITLE
Reviewers 1+4: Using Javascript doesn’t appear a right choice.

### ISSUE THREAD

**Issue by mariosky** [JJ/modeling-volunteer-computing#31]
Given that the motivation of these kinds of distributed models is to solve complex problems, using Javascript doesn’t appear a right choice. It’s true that is a very commonly used programming language, but in the context of Web applications, not in high performance ones.

If the authors would have used as a case study a complex optimization problem then they could have provided numerical data to sustain their claims;

**Comment by mariosky** [comment]
These are two related issues.

**Comment by pacastillo** [comment]
The key is that we don't configure a HPC system, such as a cluster, but we intend to use and profit the millions and millions of CPU free cycles that could be used from smartphones, laptops or desktops.

Our system does not need the client to install new software (BOINC) that sometimes is hard to use (only for experts).

**Comment by mariosky** [comment]
Yes, and even if we have only hundreds of users, the supposed overhead of
Javascript will not matter.

**Comment by fergunet** [comment]
What do you think about this response to reviewers?

Reviewer is right: we have justified the usage of Javascript in the Introduction with the next paragraph:
"There exist other volunteer frameworks written in compiled languages, such as C++ or Java, that can achieve more performance than JavaScript. However, one of the advantages of our system is that clients do not need to install anything in their machines, just to open a regular web page. Javascript is the only language that can be executed in this way without any installation, besides the default modern browsers, such as Chrome, Safari or Firefox, that are available in almost every desktop or mobile device. Other advantage is that the source code can be directly examined by the volunteer, not being compiled as other options (such as Java Applets or ActiveX). Also, as we discuss in this paper, it can provide some extra features such as safety or operating system independence."

Also, all these features have been clarified in section "Description of the system", where these advantages, and others such as safety or operating system independence are also described.

**Comment by mariosky** [comment]
Then we also need to focus more on those advantages in the paper and argue
that
performance wise using Web Workers  at least gave us a boost.

How  we stand in the Real-Time experiments?
If we have time to run those we can convince even more.
