### ISSUE TITLE
Reviewer 1: Title is misleading

### ISSUE THREAD

**Issue by mariosky** [JJ/modeling-volunteer-computing#32]
The title “Volunteers in the Clouds: an Architecture for Low Cost and Potentially Massive Distributed Evolutionary Computation” seems to suggest that the volunteers run in the cloud, but that is not the case: the server run in the cloud and the volunteers do in the browsers of common PCs and laptops.

**Comment by pacastillo** [comment]
I suggest to remove “Volunteers in the Clouds:" from the title, and maybe change it by "Volunteer computing based on" :
"Volunteer Computing based on an Architecture for Low Cost and Potentially Massive Distributed Evolutionary Computation”

**Comment by mariosky** [comment]
The word massive in the title is giving us problems.
Why not change it to something about sharing resources?.
Also lets not forget about volunteers, they can be a resource too and they cannot be replaced by any super computer

I propose something like:
A Web Based Architecture to Harness Volunteer Computational Resources for Low Cost Distributed Evolutionary Computation

Some keywords that can also be included in title: Asynchronous, Pool-Based, Javascript-Based, Open Source software.

Lets not forget this issue is about software.

**Comment by pacastillo** [comment]
I like this title. Much more descriptive of the paper contents.
