### ISSUE TITLE
Reviewer 1: The paper abstract does not properly summarize the paper contents

### ISSUE THREAD

**Issue by mariosky** [JJ/modeling-volunteer-computing#33]
The paper abstract does not properly summarize the paper contents. It says that “That is why in this paper we present NodIO, a client-server architecture for distributed evolutionary algorithms !”, but there are two versions of the architecture, as stated later in the conclusions: “In this paper two versions of a client-server architecture for volunteer and distributed evolutionary !”. That second version is neither commented in the introduction.

**Comment by mariosky** [comment]
Some highlights that can be mentioned in the abstract:
"this paper presents one of the few experiments that uses computational resources that are as dissimilar as smartphones and powerful laptops or desktop computers in a research center."

**Comment by pacastillo** [comment]
We have to make the reviewers understand that our system is not intended to be run in a HPC system, but in any platform (mobile, laptops, desktops) using any SO, and without the need of installing software, having knowledge about the problems or the metaheuristics, etc.

**Comment by mariosky** [comment]
The problem is that in the paper, there are some statements about
a minimum performance required in order to be an useful system.

But yours is a valid point, that needs to be clearly stated in the paper as
an objective.
