### ISSUE TITLE
Rev 2: There are some typos and phrases that need rewriting.

### ISSUE THREAD

**Issue by mariosky** [JJ/modeling-volunteer-computing#40]
There are some typos and phrases that need rewriting.

**Comment by JJ** [comment]
Please spell check the paper so far and revise grammar.

**Comment by JJ** [comment]
@unintendedbear can help too.

**Comment by unintendedbear** [comment]
I'm on it, actually

**Comment by fergunet** [comment]
Suggestion: should we emphasize in italic the reviewer's comments? (the ones in the {quote} sections). I think it could improve readability.

**Comment by JJ** [comment]
@fergunet Do it or don't do it. Don't "should we"
