### ISSUE TITLE
Rev 3: Description of system

### ISSUE THREAD

**Issue by mariosky** [JJ/modeling-volunteer-computing#50]
Highlight these issues: 
Heterogenity: When using HTML5 only modern browsers can participate. Also Windows Phone and Android 2.2-4.3 are excluded.
Adaptiveness: Only 5 different users that permanently participated are not enough to asses the scalability of the system. 
Safety: Source code is sent to clients,  the could access sensitive data. Results could be altered.

**Comment by pacastillo** [comment]
I'll search for data related to the % of Android OS versions used nowadays.
In any case, most people install and use Chrome for Android and Chrome for iOS (just focusing on mobile platforms), so users can run our experiments despite their Android version   ;)

**Comment by pacastillo** [comment]
Paying attention to the "security issue": is it possible the JS code sent to the clients to be ofuscated/encrypted prior to be sent?

**Comment by mariosky** [comment]
I was reading about trust in
http://boinc.berkeley.edu/trac/wiki/VolunteerComputing .
So it is an understanding of that risk and is both ways.
- Volunteers are effectively anonymous; although they may be required to
  register and supply email address or other information, they are not linked
  to a real-world identity.
- Because of their anonymity, volunteers are not _accountable_ to
  projects. If a volunteer misbehaves in some way (for example, by
  intentionally returning incorrect computational results) the project cannot
  prosecute or discipline the volunteer.
- Volunteers must _trust_ projects in several ways:
  - The volunteer trusts the project to provide applications that don't
    damage their computer or invade their privacy.
  - The volunteer trusts that the project is truthful about what work
    is being done by its applications, and how the resulting intellectual
    property will be used.
  - The volunteer trusts the project to follow proper security
    practices, so that hackers cannot use the project as a vehicle for
    malicious activities.

**Comment by mariosky** [comment]
Maybe this is an appropriate reference:
http://dl.acm.org/citation.cfm?id=1772766

**Comment by mariosky** [comment]
Comment to reviewer:
We highlighted the issues presented and also added a brief explanation about security concerns in volunteer systems.
