### ISSUE TITLE
Rev 3: Skeptical about the real value of experiments.

### ISSUE THREAD

**Issue by mariosky** [JJ/modeling-volunteer-computing#51]
Choose other problem for experiments or change the focus to the behavior analysis of volunteers in a distributed computing system.

**Comment by mariosky** [comment]
Lo pongo como un issue distinto porque resalta la posibilidad de que los experimentos aun sirvan para demostrar el comportamiento de los voluntarios.

**Comment by afdez** [comment]
Hola Mario,

encantado de asludarte. JJ me pasó el para leerlo y me dijo que podía ir aportando mi punto de vista.
Por ahora, acabo de proponer un problema que es muy atractivo desde diferentes puntos de vista. Creo que está marcado en el Issue #56.
