### ISSUE TITLE
Draw some conclusions from the baseline measurements

### ISSUE THREAD

**Issue by JJ** [JJ/modeling-volunteer-computing#59]
Put them at the end of the section. If needed, modify responses to reviewers.

**Comment by pacastillo** [comment]
In the responses to reviewer 3, I would change the sentence:
 "Windows Phone, for instance and maybe fortunately, is not too common."
to:
 "Windows Phone for instance is not too common."

**Comment by mariosky** [comment]
Im confused,
 Conclusions from the baseline with respect to the Rastrigin's  experiment?

**Comment by mariosky** [comment]
Oh, I get it  from the 10k Evaluations
