### ISSUE TITLE
Define acronyms and change only those that are really needed

### ISSUE THREAD

**Issue by JJ** [JJ/modeling-volunteer-computing#61]
Please @pacastillo do this. When you're done, reassign the issue back to me.

**Comment by pacastillo** [comment]
I have fixed acronyms such as EA, EC, IP, etc.

I have deleted "FEs" acronym => I have expanded all ocurrences (3 in total).

I think that some acronyms, such as REST, POST, GET, HTTP, HTML5, CPU, API, URL should not be expanded.

**Comment by JJ** [comment]
POST is not really an acronym...
