### ISSUE TITLE
Remove subsection

### ISSUE THREAD

**Issue by JJ** [JJ/modeling-volunteer-computing#64]
And revise surroundings for continuity. Report back to me.

**Comment by mariosky** [comment]
Done in 0bfc89a6b7774ad03618b2bbb7864354327894e6

**Comment by JJ** [comment]
Did you push the changes?

**Comment by mariosky** [comment]
I did it before :)

**Comment by mariosky** [comment]
I removed single subsections

**Comment by JJ** [comment]
Yep, I noticed. Just one to go!

2015-12-15 20:17 GMT+01:00 Mario Garcia Valdez notifications@github.com:

> I did it before :)
> 
> On Tuesday, 15 December 2015, Juan Julián Merelo Guervós <
> notifications@github.com> wrote:
> 
> > Did you push the changes?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/JJ/modeling-volunteer-computing/issues/64#issuecomment-164858647
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JJ/modeling-volunteer-computing/issues/64#issuecomment-164860666
> .

## 

JJ
