### ISSUE TITLE
R2 and R4: Increase font size

### ISSUE THREAD

**Issue by mariosky** [JJ/modeling-volunteer-computing#71]
Additionally, the axis labels and legends in most of the figures are unreadable, please increase its font size.

**Comment by mariosky** [comment]
I can work with this at the Image level if is needed.

**Comment by JJ** [comment]
I can do that, Mario, no problem.

2015-12-14 16:15 GMT+01:00 Mario Garcia Valdez notifications@github.com:

> I can work with this at the Image level if is needed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JJ/modeling-volunteer-computing/issues/71#issuecomment-164463360
> .

## 

JJ
