### ISSUE TITLE
R2: Threats to validity

### ISSUE THREAD

**Issue by mariosky** [JJ/modeling-volunteer-computing#72]
I strongly recommend to authors to follow the recommendations and guidelines described in:
“Experimentation in software engineering: an introduction”. Wohlin, Claes and Runeson, Per and Höst, Martin and Ohlsson, Magnus C and Regnell, Björn and Wesslén, Anders. Springer Publishing Company, Incorporated. 2012.

**Comment by mariosky** [comment]
I'm on this

**Comment by mariosky** [comment]
Before I include them in the main text, i will put the treats I see here, please include other if you can.

There are several validity threats to the design of this study.

Participants of the experiments were mainly members of our 
own social networks, mainly personal colleagues, friends 
and acquaintances, in extending this work other options 
should be considered, in order to include 
a wider audience with different motives for participation.
As participants were anonymous the amount of repeated 
participation and the effects this has in the outcome is not
known.

**Comment by JJ** [comment]
OK

2015-12-14 17:00 GMT+01:00 Mario Garcia Valdez notifications@github.com:

> Before I include them in the main text, i will put the treats I see here,
> please include other if you can.
> 
> There are several validity threats to the design of this study.
> 
> Participants of the experiments were mainly members of our
> own social networks, mainly personal colleagues, friends
> and acquaintances, in extending this work other options
> should be considered, in order to include
> a wider audiance with different motives for participation.
> As participants were anonymous the amount of repeated
> participation and the effects this has in the outcome is not
> known.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JJ/modeling-volunteer-computing/issues/72#issuecomment-164475741
> .

## 

JJ

**Comment by mariosky** [comment]
The scalability of the system was not thoroughly tested  
but for the amount of participants the basic configuration 
was mode than adequate, again more experiments are needed in order
to assess the capability both with more clients and other server
configurations. 

Although care was taken to include representative benchmarks
of real world problems, more experiments with a broader coverage 
should allow a better understanding of the practical limitations of
the architecture and the tools chosen.

**Comment by JJ** [comment]
Just include it in the test and let's be done with it.

**Comment by mariosky** [comment]
Was included in c850a3b5b6b73b11bebc2feca7ee02bc5e9a186f
