### ISSUE TITLE
Write response to reviewers

### ISSUE THREAD

**Issue by JJ** [JJ/modeling-volunteer-computing#81]
Which we didn't think was necessary in principle...

**Comment by pacastillo** [comment]
I have included the text of each one of reviewer's reviews.

However, I don't know if we should answer too to the editor's questions (I copy below):

1) Be careful with the use of acronyms. They must be defined the first time appearing in the text.  Moreover, the use of too many acronyms jeopardizes readability of the manuscript. Please, keep only those acronyms which are really needed.

2) NodIO-W2 is not presented in the abstract.

3) Check the use of system vs framework.
We recommend to use only one of these two words all along the text.

4) Considering only one subsection inside a section makes harder the paper comprehensibility.
For instance, in case of section IV, we recommend removing the caption related to subsection A and keeping everything in just one section.

5) We suggest re-writing the title of section IV as "Baseline Experiments".

6) We suggest re-writing the title of section V as "Enhancing NodIO with a web worker-based architecture"

7) Section V should be split into two sections.
The new section may be entitled as "Experimental trials" and it should start at "The experiments were run in the same way as before..."
Moreover, it would be better to remove the caption of subsetion V.A.
In case you think the section is too long then you may organize it into two subsections (A. Setup and B. Results)

8) Minor typos:
Abstract. "...the user behavior follow[s] by..." ([s] is missing)
Page1. "which will be [provisionally] named NodIO" (remove [provisionally])
Page2. "SuperWeb is focused , however, in..." (there is an extra blank space)
Page2. "...in the sense [than] an extra..." ([than] must be replaced by [that])
Page3. "...most of them. [32]." (there is an extra dot)
Page4. "...a particular chromosome . Another..." (there is an extra blank space)
Page6. "...the month[s] of April..." (there is an extra [s])
Page7. "...resources or not.However..." (a blank space is missing)
Page9. "...even [it] the user brings..." ([it] must be replaced by [in case])
Page9. "...of the W2 version of NodIO..." (re-write as "of the enhanced NodIO which is called NodIO-W2")
Page13. "we used a comprehensive set of developer tools available for both browsers and desktop" (can you include a footnote with the url where such tools are available?)
Page13. "...for the [ea algorithm]" (replace [ea algorithm] by [EA])
Page16. "NodIO2". Notice that the name of was NodIO-W2?
Page16. "...5 times more total cycles [that] the one with..." (replace [that] by [than])
Ref63. Check this reference.

9) The following recent reference is closely related to your paper and it should be cited:
J. Alcala-Fdez and Jose M. Alonso, "A survey of fuzzy systems software: Taxonomy, current research trends and prospects," IEEE Transactions on Fuzzy Systems, 2015. Doi:10.1109/TFUZZ.2015.2426212

**Comment by unintendedbear** [comment]
With regard to 4), just to let you know that section IV is ok but section V has an "A" subsection.

I mean: either we split V into two sections or we put the results under a subsection "B"

**Comment by fergunet** [comment]
Or maybe just remove the 

```
\subsection{Experimental trials}
\label{sec:w2Exp}
```

in line 1050? Which option do you prefer @JJ @mariosky ?

**Comment by JJ** [comment]
Let me check it out...

**Comment by mariosky** [comment]
I did that change, it was section instead of subsection as proposed by the
editor

**Comment by JJ** [comment]
But you left an "orphan" section. I have added another one.

**Comment by mariosky** [comment]
No, it was suposed to be a section, it was part of a split. I let the
subsection
tag in the copy-paste by mistake. But is ok if you added another one :)

**Comment by pacastillo** [comment]
Is it possible to change the paper know?

**Comment by JJ** [comment]
There are a couple of minor changes which we hadn't addressed before.
