### ISSUE TITLE
Fetch format and adapt paper to new format

### ISSUE THREAD

**Issue by JJ** [JJ/modeling-volunteer-computing#94]
Ditto. Please do it soon. We want to have an idea of how many pages we have, how many are required and so on.

**Comment by fergunet** [comment]
Ok, I will start working on it. First question to address: should we send the version "before" the cuts? The one that finishes in this commit: 810a1bbc8f26e989c109ec1853a1bf35ce1961b8

**Comment by JJ** [comment]
No. Let's work on the latest version, and let's add from the last one if
needed. There are many changes in either of them that are not in thatversion

2016-01-25 19:42 GMT+01:00 Pablo García Sánchez notifications@github.com:

> Ok, I will start working on it. First question to address: should we send
> the version "before" the cuts? The one that finishes in this commit:
> 810a1bb
> https://github.com/JJ/modeling-volunteer-computing/commit/810a1bbc8f26e989c109ec1853a1bf35ce1961b8
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JJ/modeling-volunteer-computing/issues/94#issuecomment-174616649
> .

## 

JJ
