### ISSUE TITLE
Rewrite abstract to reflect new results and structure

### ISSUE THREAD

**Issue by JJ** [JJ/modeling-volunteer-computing#96]
And do it in time for abstract submission.

**Comment by mariosky** [comment]
Changed two words in c0dfd8d64a36c7c4890b2b128e559e2b4caf71f9

**Comment by mariosky** [comment]
About the new title:  Performance to/from the masses  :100:

**Comment by JJ** [comment]
Looks cool.

2016-01-26 18:51 GMT+01:00 Mario Garcia Valdez notifications@github.com:

> About the new title: Performance to/from the masses 100:
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JJ/modeling-volunteer-computing/issues/96#issuecomment-175140092
> .

## 

JJ
